"use client";
import {useEffect,useRef} from "react";
import {X,MessageCircle,ArrowUpRight} from "lucide-react";
import {safeUrl,ZONE} from "../lib/planning.mjs";
import {overlapDetails} from "../lib/capacity-details.mjs";
type Task={id:string;title:string;deadline:string;deadlineSource?:string;lane:string;project:string;stakeholder:string;minutes:number;status:string;output:string;sourceUrl:string};
const deadlineLabel=(value?:string)=>value==="self"?"Self-imposed":value==="external"?"External obligation":"Deadline source unknown";
const stamp=(value:string|number)=>new Date(value).toLocaleString("en-US",{timeZone:ZONE,month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
const guard="Use my safety/privacy priorities. Ask about missing facts and deadline ownership before suggesting a change. Discuss rescheduling, handoff/delegation and ways you can help draft the expected output. Do not claim anything has been rescheduled, delegated or created externally. Only propose changes for my confirmation. Calendar coverage may be provisional.";
export default function CapacityDetails({kind,tasks,analysis,reliable,onClose,onOpen,onAegis}:{kind:"open"|"conflicts"|"risks"|null;tasks:Task[];analysis:any;reliable:boolean;onClose:()=>void;onOpen:(task:any)=>void;onAegis:(prompt:string)=>void}){
 const panel=useRef<HTMLDivElement>(null),close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!kind)return;const previous=document.activeElement as HTMLElement;close.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"){const list=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]')||[]);const first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus();};},[kind]);
 if(!kind)return null;
 const open=tasks.filter(t=>t.status!=="done").sort((a,b)=>a.deadline.localeCompare(b.deadline));
 const title=kind==="open"?"Open commitments":kind==="conflicts"?"Time conflicts":"Deadlines at risk";
 const count=kind==="open"?open.length:kind==="conflicts"?analysis.conflicts.length:analysis.risks.length;
 const taskPrompt=(t:Task,reason?:string)=>`Help me ${reason?"resolve this deadline risk":"plan this open commitment"}: ${JSON.stringify({id:t.id,title:t.title,deadline:t.deadline,deadlineSource:t.deadlineSource||"unknown",minutes:t.minutes,stakeholder:t.stakeholder,output:t.output,reason})}. If the deadline source is unknown, ask whether it is self-imposed or external and who set it. Ask whether moving it is acceptable. ${guard}`;
 return <div className="modal-backdrop" onClick={onClose}><div className="modal capacity-modal" ref={panel} role="dialog" aria-modal="true" aria-labelledby="capacity-title" onClick={e=>e.stopPropagation()}>
  <div className="modal-heading"><div><span className="eyebrow">CAPACITY REVIEW · ALL LANES</span><h2 id="capacity-title">{title} <span className="quiet">({count})</span></h2></div><button ref={close} className="icon-button" aria-label="Close capacity review" onClick={onClose}><X size={20}/></button></div>
  <p className="small-copy">{kind==="conflicts"?"Each item shows the two busy events and the exact interval they share. Calendar buffers affect capacity, but are not counted as event overlaps.":kind==="risks"?"These are deadline and remaining-work checks across all lanes. A time shortfall reflects cumulative work due by that date, not just this task.":"Every unfinished commitment across all lanes, including work waiting on someone."}</p>
  {!reliable&&<p className="banner error">Calendar coverage is incomplete or stale. Conflicts may be missing and capacity-based deadline risks are provisional.</p>}
  {count>0&&<button className="secondary capacity-review-all" onClick={()=>onAegis(`Review ${kind==="conflicts"?"all current time conflicts":kind==="risks"?"all current at-risk deadlines":"my open commitments"} in my dashboard. ${guard}`)}><MessageCircle size={16}/> Review this list with Aegis</button>}
  <div className="capacity-list">
   {kind==="conflicts"&&analysis.conflicts.map((c:any,i:number)=>{const detail=overlapDetails(c.a,c.b);if(!detail)return null;const rows=[c.a,c.b];const taskFor=(e:any)=>tasks.find(t=>t.id===e.taskId);return <article className="capacity-card" key={`${c.a.id}:${c.b.id}:${i}`}>
    <h3 className="danger">{stamp(detail.start)} – {stamp(detail.end)}</h3><p className="overlap-label">{detail.minutes} minutes overlapping</p>
    <div className="overlap-timeline" aria-label={`Shared interval: ${stamp(detail.start)} to ${stamp(detail.end)}`}>{rows.map((e:any,n:number)=><div className="overlap-track" key={n} role="img" aria-label={`${e.title}: ${stamp(e.start)} to ${stamp(e.end)}; highlighted shared interval`}><span style={{left:`${detail.bars[n].left}%`,width:`${detail.bars[n].width}%`}}/><i style={{left:`${detail.highlight.left}%`,width:`${detail.highlight.width}%`}}/></div>)}</div>
    {rows.map((e:any,n:number)=><div className="conflict-event" key={n}><strong>{e.title}</strong><p>{stamp(e.start)} – {stamp(e.end)} · {e.calendar||"Partheanon work block"}</p>{taskFor(e)?<button className="text-button" onClick={()=>onOpen(taskFor(e))}>Edit commitment</button>:safeUrl(e.url)&&<a className="text-button" href={safeUrl(e.url)} target="_blank" rel="noreferrer">Open calendar event <ArrowUpRight size={14}/></a>}</div>)}
    <button className="secondary" onClick={()=>onAegis(`Help resolve this overlap: ${JSON.stringify({events:rows.map(e=>({id:e.id,taskId:e.taskId,title:e.title,start:e.start,end:e.end,calendar:e.calendar})),overlapStart:new Date(detail.start).toISOString(),overlapEnd:new Date(detail.end).toISOString()})}. Ask which commitment is fixed, who depends on it, and whether rescheduling or delegation is possible. ${guard}`)}><MessageCircle size={16}/> Resolve with Aegis</button>
   </article>;})}
   {(kind==="open"?open.map(task=>({task,reason:""})):kind==="risks"?analysis.risks:[]).map(({task:t,reason}:any)=><article className="capacity-card" key={t.id}><button className="task-main" onClick={()=>onOpen(t)}><strong>{t.title}</strong></button><p>{t.lane} · {t.project||"No project"} · {t.minutes} min remaining · {t.status==="waiting"?"Waiting on someone":t.status==="doing"?"In progress":"Open"}</p><p>Due {t.deadline} · <span className="pill">{deadlineLabel(t.deadlineSource)}</span></p>{reason&&<p className="danger">{reason}</p>}{t.stakeholder&&<p>Depending on this: {t.stakeholder}</p>}{t.output&&<p>Expected output: {t.output}</p>}<div className="capacity-actions"><button className="secondary" onClick={()=>onOpen(t)}>Edit commitment</button><button className="secondary" onClick={()=>onAegis(taskPrompt(t,reason))}><MessageCircle size={16}/> {kind==="risks"?"Review risk with Aegis":"Plan with Aegis"}</button></div></article>)}
   {count===0&&<p className="empty">{kind==="conflicts"?"No overlaps found in the cached calendar view.":kind==="risks"?"No deadlines currently flagged by the capacity checks.":"No open commitments."}</p>}
  </div>
 </div></div>;
}
