"use client";
import {useState} from "react";
import {descendants,workTotals} from "../lib/task-work.mjs";
import {dateKey} from "../lib/planning.mjs";
export type WorkLog={id:string;taskId:string;workedOn:string;minutes:number;aiMinutes:number;skills:string[];notes:string};
export default function CommitmentWork({task,tasks,logs,saving,onParent,onOpen,onAdd,onLog,onRemove}:{task:any;tasks:any[];logs:WorkLog[];saving:boolean;onParent:(id:string|null)=>void;onOpen:(task:any)=>void;onAdd:()=>void;onLog:(log:WorkLog)=>Promise<void>;onRemove:(id:string)=>Promise<void>}){
 const [draft,setDraft]=useState({workedOn:dateKey(),minutes:60,aiMinutes:0,skills:"",notes:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const saved=tasks.some(t=>t.id===task.id),children=tasks.filter(t=>t.parentId===task.id),blocked=descendants(tasks,task.id),totals=workTotals(tasks,logs,task.id);
 const submit=async()=>{setBusy(true);setError("");try{await onLog({...draft,id:crypto.randomUUID(),taskId:task.id,skills:draft.skills.split(",").map(s=>s.trim()).filter(Boolean)});setDraft({...draft,notes:""});}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <section className="commitment-work"><h3>Parent & subtasks</h3><label>Parent commitment<select value={task.parentId||""} onChange={e=>onParent(e.target.value||null)}><option value="">Standalone commitment</option>{tasks.filter(t=>t.id!==task.id&&!blocked.has(t.id)).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>
 <p className="footnote">Remaining work is for this task only. Use 0 when all work belongs to subtasks. Subtasks carry their own estimates and deadlines, so capacity doesn’t count the same work twice. Complete all subtasks before completing a parent.</p>
 {children.map(c=><button type="button" className={`subtask-link ${c.status==="done"?"source-completed":""}`} key={c.id} onClick={()=>onOpen(c)}><span>{c.title}</span><small>{c.status==="done"?"Done":c.deadline}</small></button>)}
 <button type="button" className="secondary" disabled={!saved||saving||task.status==="done"} onClick={onAdd}>Add subtask</button>{!saved&&<p className="footnote">Save this commitment first to add subtasks or log work.</p>}
 <h3>Actual work</h3><div className="work-summary"><span><strong>{totals.own.minutes} min</strong> on this task · {totals.own.aiMinutes} min AI-assisted</span>{children.length>0&&<span><strong>{totals.family.minutes} min</strong> including subtasks · {totals.family.aiMinutes} min AI-assisted</span>}</div>
 <p className="footnote">Elapsed work includes AI-assisted time. Parallel human and AI work is counted once. Skills describe what was used; they don’t automatically change duration. Logged work is separate from the remaining estimate above.</p>
 {logs.filter(l=>l.taskId===task.id).sort((a,b)=>b.workedOn.localeCompare(a.workedOn)).map(l=><div className="work-log" key={l.id}><div><strong>{l.workedOn} · {l.minutes} min</strong><small>{l.aiMinutes} min AI-assisted{l.skills.length?` · ${l.skills.join(", ")}`:""}</small><p>{l.notes}</p></div><button type="button" className="text-button" disabled={busy||saving} onClick={async()=>{setError("");setBusy(true);try{await onRemove(l.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}} aria-label={`Remove work entry ${l.workedOn} ${l.minutes} minutes`}>Remove</button></div>)}
 <button type="button" className="text-button" disabled={!saved} onClick={async()=>{try{await navigator.clipboard.writeText(`Help me close out Partheanon commitment ${task.id}: ${task.title}. Summarize the actual work performed, AI assistance, and skills used from our work together. Ask me to confirm elapsed minutes and the included AI-assisted minutes if uncertain. Record the confirmed session using log_task_work when the Partheanon integration is available; otherwise give me the fields to enter in Actual work.`);setError("Task reference copied for Aegis.");}catch{setError("Copy unavailable. Ask Aegis to review this task by its title.");}}}>Copy task reference for Aegis</button><h3>Log a work session</h3><div className="form-grid"><label>Work date · Phoenix<input type="date" value={draft.workedOn} onChange={e=>setDraft({...draft,workedOn:e.target.value})}/></label><label>Elapsed minutes<input type="number" min={1} max={1440} value={draft.minutes} onChange={e=>setDraft({...draft,minutes:Number(e.target.value)})}/></label><label>AI-assisted minutes (included)<input type="number" min={0} max={draft.minutes} value={draft.aiMinutes} onChange={e=>setDraft({...draft,aiMinutes:Number(e.target.value)})}/></label><label>Skills used<input maxLength={3000} value={draft.skills} onChange={e=>setDraft({...draft,skills:e.target.value})} placeholder="Research, drafting, coding… (comma-separated)"/></label></div><label>Work performed / output<textarea maxLength={2000} rows={2} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>
 {error&&<p role="alert" className="danger">{error}</p>}<button type="button" className="secondary" disabled={!saved||busy||saving} onClick={submit}>{busy?"Saving…":"Save work entry"}</button><p className="footnote">Each entry saves separately. When finishing with Aegis, provide the task, elapsed time, AI-assisted time, skills, and result for review. Aegis can record confirmed entries through the Partheanon integration when workspace access is enabled.</p></section>;
}
