"use client";
import {useState} from "react";
import {RefreshCw,ShieldCheck} from "lucide-react";
import {allSourceInfo,type Connection} from "../lib/connections";
export default function ConnectionHealth({connections,reconnectHref}:{connections:Connection[];reconnectHref:string}){
 const [report,setReport]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[retryAt,setRetryAt]=useState(0);
 async function check(){if(busy||Date.now()<retryAt)return;setBusy(true);setError("");try{const r=await fetch("/api/connection-health",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data:any=await r.json();if(!r.ok)throw new Error(data.error||"Could not check service accounts.");setReport(data);setRetryAt(Date.now()+Math.max(0,...data.services.map((s:any)=>s.retryAfterMs||0)));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const configured=allSourceInfo(connections);
 return <section className="panel connection-health"><div className="panel-heading"><div><h2>Plugin fallback routing</h2><p>These are the plugin routes. Direct account connections above use independent authorizations.</p></div><button className="secondary" disabled={busy} onClick={check}><RefreshCw size={16}/> {busy?"Checking…":"Check account routing"}</button></div>{error&&<p className="danger connection-health-note" role="alert">{error}</p>}{report?<><p className="connection-health-note">Checked {new Date(report.checkedAt).toLocaleTimeString("en-US",{timeZone:"America/Phoenix",hour:"numeric",minute:"2-digit"})} Phoenix time. This checks account identity; source cards below show calendar and email reads.</p>{report.services.map((s:any)=>{const waiting=Object.entries(configured).filter(([k,c])=>(k===s.id||k.endsWith(`:${s.id}`))&&c.account.toLowerCase()!==s.account?.toLowerCase()).map(([,c])=>c.account);return <div className="settings-row" key={s.id}><div><strong>{s.name}</strong>{s.status==="success"?<><p><ShieldCheck size={14}/> Plugin read verified · Site receives <strong>{s.account}</strong></p>{waiting.length>0&&<p className="danger">Waiting for another account route: {waiting.join(", ")}. {s.accountSelector===false?"This hosted service has no account selector; adding accounts to the plugin does not create additional live routes.":"Review Site account selection before retrying."}</p>}</>:<p className="danger">{s.message||"Access not verified"}</p>}</div><a className="secondary" href={s.settingsUrl} target="_blank" rel="noopener noreferrer">Manage {s.name}</a></div>;})}<p className="connection-health-note">For a routing mismatch, your provider credentials may already be valid. Repeatedly reconnecting the provider will not expand the Site’s account routing. <a href={reconnectHref} target="_top" className="text-button">Review Site account selection</a></p></>:<p className="connection-health-note">If setup says “Different account selected,” check routing first. The account may be authorized in ChatGPT while this Site receives another account.</p>}</section>;
}
