"use client";
import {Moon,Sun,Monitor,Settings2,ShieldCheck,Download,Plug,RefreshCw,ArrowUpRight,LogOut} from "lucide-react";
import type {Theme} from "../lib/theme";
const modes=[{id:"dark",name:"Dark",description:"Deep green, sage, and soft teal",icon:Moon},{id:"light",name:"Light",description:"Warm paper and gentle greens",icon:Sun},{id:"system",name:"Use device theme",description:"Follow this device’s appearance",icon:Monitor}] as const;
export default function SettingsPage({preferences,saving,onTheme,onWorkHours,onConnections,onRefresh,refreshing,onExport}:{preferences:{startHour:number;endHour:number;theme:Theme};saving:boolean;onTheme:(t:Theme)=>void;onWorkHours:()=>void;onConnections:()=>void;onRefresh:()=>void;refreshing:boolean;onExport:()=>void}){
return <div className="settings-grid"><section className="panel settings-appearance"><div className="panel-heading"><div><h2>Appearance</h2><p>A softer view for every part of your day. Your choice applies to every screen and dialog.</p></div><Moon size={20}/></div><div className="theme-options" role="group" aria-label="Application theme">{modes.map(m=><button key={m.id} className={`theme-choice ${preferences.theme===m.id?"selected":""}`} aria-pressed={preferences.theme===m.id} disabled={saving} onClick={()=>onTheme(m.id)}><m.icon size={23}/><strong>{m.name}</strong><small>{m.description}</small><span className={`theme-preview preview-${m.id}`} aria-hidden="true"><i/><i/><i/></span></button>)}</div><p className="settings-note">Dark is the default. Preferences are saved privately across your devices; device theme follows each device independently. Browser and provider permission pages use their own theme controls.</p></section>
<section className="panel"><div className="panel-heading"><div><h2>Planning preferences</h2><p>Protect time that fits your working day.</p></div><Settings2 size={20}/></div><div className="settings-row"><div><strong>Work hours</strong><p>Weekdays {String(preferences.startHour).padStart(2,"0")}:00–{String(preferences.endHour).padStart(2,"0")}:00</p></div><button className="secondary" onClick={onWorkHours}>Edit work hours</button></div><div className="settings-row"><div><strong>Time zone & calendar buffer</strong><p>America/Phoenix · 15 minutes around busy events. Weekends are outside proposed work time.</p></div></div></section>
<section className="panel"><div className="panel-heading"><div><h2>Accounts & updates</h2><p>Review what Partheanon can currently see.</p></div><Plug size={20}/></div><div className="settings-row"><div><strong>Connections</strong><p>Add accounts and review verification, errors, coverage, and last-read times.</p></div><button className="secondary" onClick={onConnections}>Manage connections</button></div><div className="settings-row"><div><strong>Source refresh</strong><p>Every five minutes while open. Background and instant sync are not available yet.</p></div><button className="secondary" disabled={refreshing} onClick={onRefresh}><RefreshCw size={15}/>{refreshing?"Refreshing…":"Refresh now"}</button></div><div className="settings-row"><div><strong>Provider account access</strong><p>In ChatGPT, open Settings → Plugins (or Apps), then select the relevant app and review its connected accounts.</p></div><a className="secondary" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">Open ChatGPT <ArrowUpRight size={14}/></a></div></section>
<section className="panel"><div className="panel-heading"><div><h2>Privacy & housekeeping</h2><p>Your commitments remain yours.</p></div><ShieldCheck size={20}/></div><div className="settings-row"><div><strong>Download your records</strong><p>Export commitments, protected blocks, preferences, and saved account setup records as JSON. Email and meeting-note caches are excluded. Keep the downloaded file private.</p></div><button className="secondary" onClick={onExport}><Download size={15}/> Export records</button></div><div className="settings-row"><div><strong>Sign out</strong><p>End this browser’s Partheanon session. Saved records and provider permissions remain.</p></div><a className="secondary" href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut size={15}/> Sign out</a></div><p className="settings-note">Removing an account setup in Connections clears its cached reads. To revoke provider access, manage the account in ChatGPT. Task and calendar exports are snapshots.</p></section>
<section className="panel settings-about"><div className="panel-heading"><div><span className="eyebrow">PARTHEANON · FORGE & AEGIS</span><h2>About Partheanon</h2><p>Your commitments, in perspective.</p></div></div><div className="about-copy"><p>Created by Rob Brown (Forge) to bring work, service, business, and personal commitments into one calm place. Aegis is the intended planning partner: helping track stakeholders, tasks, time, and outcomes while guarding room to do the work.</p><p>This version provides calendar views, commitments, projects, meeting-note coverage, inbox review, and rule-based capacity checks. Aegis’s direct Site integration still requires workspace permission. Additional account reads depend on provider access; Notion coverage is partial and direct iCloud sync is unavailable.</p><div className="about-links"><a className="secondary" href="https://github.com/RobBrown7/Partheanon" target="_blank" rel="noopener noreferrer">Project & source <ArrowUpRight size={14}/></a><a className="text-button" href="https://help.openai.com/en/articles/20001494-connecting-and-managing-app-accounts-in-chatgpt" target="_blank" rel="noopener noreferrer">Account connection help <ArrowUpRight size={14}/></a></div><small>Settings release · October 2026 · Private dashboard, public source archive</small></div></section></div>;
}
