"use client";
import {useRef,useState} from "react";
import {Plus,List,Eye,Pencil,X} from "lucide-react";
import {dateKey} from "../lib/planning.mjs";
export const WORK_TEXT_LIMIT=20000;
export type WorkOutput={id:string;taskId:string;workedOn:string;notes:string};
// Render a small Markdown subset as React text nodes; pasted HTML is never executed.
function inline(text:string){return text.split(/(\*\*[^*\n]+\*\*|`[^`\n]+`)/g).map((part,i)=>part.startsWith("**")&&part.endsWith("**")?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith("`")&&part.endsWith("`")?<code key={i}>{part.slice(1,-1)}</code>:part);}
export function WorkText({text}:{text:string}){
 const lines=text.replace(/\r\n?/g,"\n").split("\n"),blocks=[];
 for(let i=0;i<lines.length;){const line=lines[i];if(!line.trim()){i++;continue;}
  if(/^\s*[-*•]\s+/.test(line)){const items=[];while(i<lines.length&&/^\s*[-*•]\s+/.test(lines[i])){items.push(<li key={i}>{inline(lines[i].replace(/^\s*[-*•]\s+/,""))}</li>);i++;}blocks.push(<ul key={`list-${i}`}>{items}</ul>);}
  else if(/^#{1,3}\s+/.test(line)){blocks.push(<h4 key={i}>{inline(line.replace(/^#{1,3}\s+/,""))}</h4>);i++;}
  else{const paragraphs=[];while(i<lines.length&&lines[i].trim()&&!/^\s*[-*•]\s+|^#{1,3}\s+/.test(lines[i])){paragraphs.push(lines[i]);i++;}blocks.push(<p key={`p-${i}`}>{inline(paragraphs.join("\n"))}</p>);}
 }
 return <div className="work-text">{blocks}</div>;
}
export function WorkTextEditor({value,onChange,id}:{value:string;onChange:(v:string)=>void;id:string}){
 const input=useRef<HTMLTextAreaElement>(null),[preview,setPreview]=useState(false);
 function bullet(){const el=input.current;if(!el)return;const start=value.lastIndexOf("\n",el.selectionStart-1)+1,next=value.indexOf("\n",el.selectionEnd),end=next<0?value.length:next,selected=value.slice(start,end).split("\n").map(l=>/^\s*[-*•]\s+/.test(l)?l:`- ${l}`).join("\n"),updated=value.slice(0,start)+selected+value.slice(end);if(updated.length>WORK_TEXT_LIMIT)return;onChange(updated);requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start,start+selected.length);});}
 return <div className="work-text-editor"><div className="work-text-toolbar"><button type="button" className="secondary" disabled={preview} onClick={bullet}><List size={15}/> Bullet list</button><button type="button" className="text-button" aria-pressed={preview} onClick={()=>setPreview(v=>!v)}>{preview?<Pencil size={15}/>:<Eye size={15}/>} {preview?"Edit text":"Preview"}</button><small id={`${id}-count`}>{value.length.toLocaleString()} / {WORK_TEXT_LIMIT.toLocaleString()} characters</small></div>{preview?<div className="work-text-preview">{value?<WorkText text={value}/>:<p className="footnote">Your preview will appear here.</p>}</div>:<textarea ref={input} id={id} aria-describedby={`${id}-help ${id}-count`} maxLength={WORK_TEXT_LIMIT} rows={8} value={value} onChange={e=>onChange(e.target.value)} placeholder={'Completed work\n- Investigation and findings\n\nStill to verify\n- Follow-up and checks'}/>}<p className="footnote" id={`${id}-help`}>Paste your notes or use Bullet list. Supports - bullets, **bold**, headings, and `code`. Pending steps stay notes; they do not mark subtasks complete.</p></div>;
}
export default function WorkOutputs({taskId,saved,saving,entries,onSave,onRemove}:{taskId:string;saved:boolean;saving:boolean;entries:WorkOutput[];onSave:(entry:WorkOutput)=>Promise<void>;onRemove:(id:string)=>Promise<void>}){
 const [draft,setDraft]=useState<WorkOutput|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(){if(!draft||busy||saving)return;setBusy(true);setError("");try{await onSave(draft);setDraft(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section className="work-outputs"><h3>Work performed / output</h3><p className="footnote">Keep dated findings, delivered outputs, and steps still to verify. These notes save separately and do not add elapsed time.</p>{entries.filter(e=>e.taskId===taskId).sort((a,b)=>b.workedOn.localeCompare(a.workedOn)).map(e=><article className="work-output-entry" key={e.id}><div className="work-output-heading"><strong>{e.workedOn} · Work / output</strong><div><button type="button" className="text-button" disabled={busy||saving||!!draft} onClick={()=>{setError("");setDraft({...e});}}>Edit</button><button type="button" className="text-button" disabled={busy||saving||!!draft} onClick={async()=>{setError("");setBusy(true);try{await onRemove(e.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}} aria-label={`Remove work output ${e.workedOn}`}>Remove</button></div></div><WorkText text={e.notes}/></article>)}{draft?<div className="work-output-draft"><label htmlFor="work-output-date">Work / output date · Phoenix</label><input id="work-output-date" type="date" value={draft.workedOn} onChange={e=>setDraft({...draft,workedOn:e.target.value})}/><label htmlFor="work-output-notes">Work performed / output</label><WorkTextEditor key={draft.id} id="work-output-notes" value={draft.notes} onChange={notes=>setDraft({...draft,notes})}/><div className="work-output-buttons"><button type="button" className="secondary" disabled={busy||saving} onClick={()=>{setDraft(null);setError("");}}><X size={15}/> Cancel</button><button type="button" className="primary" disabled={busy||saving||!draft.notes.trim()||!draft.workedOn} onClick={save}>{busy?"Saving…":"Save work / output"}</button></div></div>:<button type="button" className="secondary" disabled={!saved||busy||saving} onClick={()=>{setError("");setDraft({id:crypto.randomUUID(),taskId,workedOn:dateKey(),notes:""});}}><Plus size={15}/> Add Work Performed/Output</button>}{!saved&&<p className="footnote">Save the commitment first to add a work/output entry.</p>}{error&&<p className="danger" role="alert">{error}</p>}</section>;
}
