import {env} from "cloudflare:workers";
import {and,eq,lt,lte} from "drizzle-orm";
import {z} from "zod";
import {getDb} from "../db";
import {oauthClients,oauthStates,oauthAccounts} from "../db/schema";
import {readState} from "./repository";
import {allSourceInfo} from "./connections";
import {nonce,challenge,seal,unseal} from "./oauth-crypto.mjs";
export const providerSchema=z.enum(["google","microsoft"]);
type Provider=z.infer<typeof providerSchema>;
const origin="https://partheanon-forge.athena-works-8404.chatgpt.site";
export const providers={google:{authorization:"https://accounts.google.com/o/oauth2/v2/auth",token:"https://oauth2.googleapis.com/token",scopes:["openid","email","https://www.googleapis.com/auth/calendar.readonly","https://www.googleapis.com/auth/gmail.readonly"]},microsoft:{authorization:"https://login.microsoftonline.com/common/oauth2/v2.0/authorize",token:"https://login.microsoftonline.com/common/oauth2/v2.0/token",scopes:["openid","email","offline_access","https://graph.microsoft.com/User.Read","https://graph.microsoft.com/Mail.Read","https://graph.microsoft.com/Calendars.Read"]}};
const secret=()=>{const value=(env as unknown as Record<string,string>).OAUTH_ENCRYPTION_KEY;if(!value)throw new Error("Direct connections need server encryption configured.");return value;};
const aad=(owner:string,provider:string,account="client")=>JSON.stringify([owner,provider,account]);
export const callbackUrl=(provider:Provider)=>`${origin}/api/oauth/callback/${provider}`;
async function client(owner:string,provider:Provider){const [row]=await getDb().select().from(oauthClients).where(and(eq(oauthClients.owner,owner),eq(oauthClients.provider,provider)));if(!row)throw new Error(`Set up the ${provider==="google"?"Google":"Microsoft"} app registration first.`);return unseal(row.sealed,secret(),aad(owner,provider));}
export async function saveClient(owner:string,input:unknown){const c=z.object({provider:providerSchema,clientId:z.string().trim().min(1).max(500),clientSecret:z.string().trim().min(1).max(2000)}).strict().parse(input);const existing=await getDb().select().from(oauthAccounts).where(and(eq(oauthAccounts.owner,owner),eq(oauthAccounts.provider,c.provider)));if(existing.length)throw new Error("Disconnect this provider's direct accounts before changing its app registration.");const sealed=await seal({clientId:c.clientId,clientSecret:c.clientSecret},secret(),aad(owner,c.provider));await getDb().delete(oauthStates).where(and(eq(oauthStates.owner,owner),eq(oauthStates.provider,c.provider)));await getDb().insert(oauthClients).values({owner,provider:c.provider,sealed,updatedAt:new Date().toISOString()}).onConflictDoUpdate({target:[oauthClients.owner,oauthClients.provider],set:{sealed,updatedAt:new Date().toISOString()}});return {configured:true};}
export async function directStatus(owner:string){const db=getDb();const [clients,accounts]=await Promise.all([db.select({provider:oauthClients.provider}).from(oauthClients).where(eq(oauthClients.owner,owner)),db.select({provider:oauthAccounts.provider,account:oauthAccounts.account,updatedAt:oauthAccounts.updatedAt}).from(oauthAccounts).where(eq(oauthAccounts.owner,owner))]);return {encryptionReady:!!(env as unknown as Record<string,string>).OAUTH_ENCRYPTION_KEY,clients:clients.map(c=>c.provider),accounts,callbackUrls:{google:callbackUrl("google"),microsoft:callbackUrl("microsoft")}};}
export async function startOAuth(owner:string,input:unknown){const {provider,account}=z.object({provider:providerSchema,account:z.string().email().transform(s=>s.toLowerCase())}).strict().parse(input);const state=await readState(owner);const known=Object.entries(allSourceInfo(state.connections)).some(([key,s])=>s.account.toLowerCase()===account&&(provider==="google"?(key==="google"||key==="gmail"||key.endsWith(":google")||key.endsWith(":gmail")):(key==="outlook"||key==="unityMail"||key.endsWith(":outlook")||key.endsWith(":unityMail"))));if(!known)throw new Error("Save this account in Connections before connecting it directly.");const c=await client(owner,provider),stateKey=nonce(),verifier=nonce();await getDb().delete(oauthStates).where(lt(oauthStates.expiresAt,Date.now()));await getDb().insert(oauthStates).values({state:stateKey,owner,provider,account,verifier,expiresAt:Date.now()+600000,used:false});const url=new URL(providers[provider].authorization);const params={client_id:c.clientId,redirect_uri:callbackUrl(provider),response_type:"code",scope:providers[provider].scopes.join(" "),state:stateKey,code_challenge:await challenge(verifier),code_challenge_method:"S256",login_hint:account,prompt:provider==="google"?"consent select_account":"select_account",...(provider==="google"?{access_type:"offline",include_granted_scopes:"true"}:{response_mode:"query"})};url.search=new URLSearchParams(params).toString();return {url:url.href};}
async function tokenRequest(provider:Provider,body:Record<string,string>){const r=await fetch(providers[provider].token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(body),signal:AbortSignal.timeout(20000)});const data:any=await r.json();if(!r.ok)throw new Error(data.error==="invalid_grant"?"Provider authorization expired or was revoked. Reconnect this account.":"Provider token exchange failed. Check app registration and reconnect.");if(typeof data.access_token!=="string"||!Number.isFinite(Number(data.expires_in)))throw new Error("Provider did not return a usable authorization.");return data;}
export async function completeOAuth(owner:string,provider:Provider,stateKey:string,code:string){if(stateKey.length>200||code.length>6000)throw new Error("Invalid authorization response");const db=getDb();const [state]=await db.select().from(oauthStates).where(and(eq(oauthStates.state,stateKey),eq(oauthStates.owner,owner),eq(oauthStates.provider,provider)));if(!state||state.used||state.expiresAt<Date.now())throw new Error("Authorization request expired or already used. Start again.");const claimed=await db.update(oauthStates).set({used:true}).where(and(eq(oauthStates.state,stateKey),eq(oauthStates.used,false))).returning();if(!claimed.length)throw new Error("Authorization already attempted.");const c=await client(owner,provider),data=await tokenRequest(provider,{grant_type:"authorization_code",code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:callbackUrl(provider),code_verifier:state.verifier});const r=await fetch(provider==="google"?"https://openidconnect.googleapis.com/v1/userinfo":"https://graph.microsoft.com/v1.0/me?$select=mail,userPrincipalName",{headers:{Authorization:`Bearer ${data.access_token}`},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error("Could not verify the provider account identity.");const profile:any=await r.json(),actual=String(provider==="google"?profile.email:profile.mail||profile.userPrincipalName||"").trim().toLowerCase();if(actual!==state.account||(provider==="google"&&profile.email_verified!==true))throw new Error("The authorized account does not match the requested email. No account was connected.");const existing=await storedAccount(owner,provider,actual);const previous=existing?await unseal(existing.sealed,secret(),aad(owner,provider,actual)):null;const refresh=data.refresh_token||previous?.refresh_token;if(!refresh)throw new Error("Provider did not grant offline access. Reconnect and allow offline access.");const payload={access_token:data.access_token,refresh_token:refresh,expiresAt:Date.now()+Number(data.expires_in)*1000,scope:data.scope||providers[provider].scopes.join(" ")};if(data.scope){const granted=new Set(data.scope.split(" "));const required=provider==="google"?providers[provider].scopes.filter(s=>s.startsWith("https://")):["Mail.Read","Calendars.Read","User.Read"];if(required.some(s=>!granted.has(s)&&!granted.has("https://graph.microsoft.com/"+s)))throw new Error("Calendar and email read permissions were not both granted. Reconnect with the requested read permissions.");}const sealed=await seal(payload,secret(),aad(owner,provider,actual));await db.insert(oauthAccounts).values({owner,provider,account:actual,sealed,updatedAt:new Date().toISOString()}).onConflictDoUpdate({target:[oauthAccounts.owner,oauthAccounts.provider,oauthAccounts.account],set:{sealed,updatedAt:new Date().toISOString()}});return {account:actual};}
async function storedAccount(owner:string,provider:Provider,account:string){const [row]=await getDb().select().from(oauthAccounts).where(and(eq(oauthAccounts.owner,owner),eq(oauthAccounts.provider,provider),eq(oauthAccounts.account,account.toLowerCase())));return row;}
export async function directToken(owner:string,provider:Provider,account:string){
 const db=getDb(),where=and(eq(oauthAccounts.owner,owner),eq(oauthAccounts.provider,provider),eq(oauthAccounts.account,account.toLowerCase()));
 for(let attempt=0;attempt<24;attempt++){
  const row=await storedAccount(owner,provider,account);if(!row)return null;
  let data=await unseal(row.sealed,secret(),aad(owner,provider,row.account));if(data.expiresAt>Date.now()+120000)return data.access_token as string;
  const claimed=await db.update(oauthAccounts).set({refreshUntil:Date.now()+60000}).where(and(where,lte(oauthAccounts.refreshUntil,Date.now()))).returning();
  if(!claimed.length){await new Promise(r=>setTimeout(r,500));continue;}
  try{const c=await client(owner,provider),renewed=await tokenRequest(provider,{grant_type:"refresh_token",refresh_token:data.refresh_token,client_id:c.clientId,client_secret:c.clientSecret,...(provider==="microsoft"?{scope:providers[provider].scopes.join(" ")}:{})});data={...data,access_token:renewed.access_token,refresh_token:renewed.refresh_token||data.refresh_token,expiresAt:Date.now()+Number(renewed.expires_in)*1000};const sealed=await seal(data,secret(),aad(owner,provider,row.account));const updated=await db.update(oauthAccounts).set({sealed,updatedAt:new Date().toISOString()}).where(and(where,eq(oauthAccounts.sealed,row.sealed))).returning();if(!updated.length)throw new Error("Direct authorization changed while refreshing. Retry the source read.");return data.access_token as string;}finally{await db.update(oauthAccounts).set({refreshUntil:0}).where(where);}
 }
 throw new Error("This account is refreshing its authorization. Try again shortly.");
}
export async function disconnectDirect(owner:string,input:unknown){const {provider,account}=z.object({provider:providerSchema,account:z.string().email()}).strict().parse(input);await getDb().delete(oauthStates).where(and(eq(oauthStates.owner,owner),eq(oauthStates.provider,provider),eq(oauthStates.account,account.toLowerCase())));await getDb().delete(oauthAccounts).where(and(eq(oauthAccounts.owner,owner),eq(oauthAccounts.provider,provider),eq(oauthAccounts.account,account.toLowerCase())));return {disconnected:true};}
