import {directToken} from "./direct-oauth";
import {normalizeEvents,normalizeEmails,dateKey,dayAt,plusDays} from "./planning.mjs";
import {saveSnapshot} from "./repository";
export async function loadDirect(owner:string,source:string,offset:number,account:string,lane:string,snapshotKey:string){
 const provider=source==="google"||source==="gmail"?"google":"microsoft",token=await directToken(owner,provider,account);if(!token)return null;
 const notes:string[]=[],payload:any={account,events:[],emails:[],partial:false,notes,connectionMode:"direct"};
 const api=async(path:string)=>{const host=provider==="google"?"https://www.googleapis.com":"https://graph.microsoft.com";const url=new URL(path,host);if(url.origin!==host)throw new Error("Invalid provider page URL");const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,...(provider==="microsoft"?{Prefer:'outlook.timezone="UTC"'}:{})},signal:AbortSignal.timeout(20000)});if(!r.ok){if(r.status===401)throw new Error("Direct account authorization expired. Reconnect this account.");if(r.status===403)throw new Error("Provider denied access. Check API enablement, read scopes, or your organization's account policy.");if(r.status===429)throw Object.assign(new Error("Provider requested a pause before another read."),{retryAfterMs:Math.max(60000,Number(r.headers.get("Retry-After")||60)*1000)});throw new Error(`Direct provider read failed (${r.status}). Saved data is retained.`);}return await r.json() as any;};
 if(source==="google"||source==="outlook"){
  const key=plusDays(dateKey(),offset),timeMin=new Date(dayAt(key)).toISOString(),timeMax=new Date(dayAt(plusDays(key,14))).toISOString();
  const listed=await api(provider==="google"?"/calendar/v3/users/me/calendarList?maxResults=100":"/v1.0/me/calendars?$top=100");const calendars=(listed.items||listed.value||[]).filter((c:any)=>provider==="microsoft"||c.primary||c.selected!==false).slice(0,10);if(!calendars.length)throw new Error("No readable calendars returned for this direct account.");if((listed.items||listed.value||[]).length>10||listed.nextPageToken||listed["@odata.nextLink"]){payload.partial=true;notes.push("Calendar list is bounded; up to 10 visible calendars are read.");}
  for(const calendar of calendars){try{let next:string|null=provider==="google"?`/calendar/v3/calendars/${encodeURIComponent(calendar.id)}/events?${new URLSearchParams({timeMin,timeMax,timeZone:"America/Phoenix",singleEvents:"true",maxResults:"100",orderBy:"startTime"})}`:`/v1.0/me/calendars/${encodeURIComponent(calendar.id)}/calendarView?${new URLSearchParams({startDateTime:timeMin,endDateTime:timeMax,"$top":"100"})}`;for(let page=0;page<4&&next;page++){const data=await api(next),raw=data.items||data.value||[];const compatible=provider==="google"?raw.map((e:any)=>({...e,url:e.htmlLink,my_response_status:e.attendees?.find((a:any)=>a.self)?.responseStatus})):raw.map((e:any)=>({...e,is_cancelled:e.isCancelled,is_all_day:e.isAllDay,show_as:e.showAs,i_cal_u_id:e.iCalUId,web_link:e.webLink,response_status:e.responseStatus}));const normalized=normalizeEvents({events:compatible},provider==="google"?"google":"outlook",calendar);payload.events.push(...normalized);if(normalized.length<compatible.filter((e:any)=>e.status!=="cancelled"&&!e.is_cancelled&&e.response_status?.response!=="declined"&&e.my_response_status!=="declined").length){payload.partial=true;notes.push(`${calendar.summary||calendar.name}: some event timestamps were not usable.`);}next=provider==="google"?(data.nextPageToken?`/calendar/v3/calendars/${encodeURIComponent(calendar.id)}/events?${new URLSearchParams({timeMin,timeMax,timeZone:"America/Phoenix",singleEvents:"true",maxResults:"100",orderBy:"startTime",pageToken:data.nextPageToken})}`:null):data["@odata.nextLink"]||null;if(next&&page===3){payload.partial=true;notes.push(`${calendar.summary||calendar.name}: first 400 events read.`);}}}catch(e:any){payload.partial=true;notes.push(`${calendar.summary||calendar.name}: ${e.message||"Read did not complete"}`);if(e.retryAfterMs)throw e;}}
  payload.windowStart=timeMin;payload.windowEnd=timeMax;
 }else if(source==="gmail"){
  const listed=await api(`/gmail/v1/users/me/messages?${new URLSearchParams({q:"in:inbox -category:promotions -category:social newer_than:14d",maxResults:"40"})}`);const emails:any[]=[];for(let i=0;i<(listed.messages||[]).length;i+=5){const batch=await Promise.allSettled(listed.messages.slice(i,i+5).map(async(m:any)=>{const d=await api(`/gmail/v1/users/me/messages/${encodeURIComponent(m.id)}?format=metadata&metadataHeaders=Subject&metadataHeaders=From`);const header=(name:string)=>d.payload?.headers?.find((h:any)=>h.name.toLowerCase()===name.toLowerCase())?.value||"";return {id:d.id,subject:header("Subject"),from_:header("From"),snippet:d.snippet,email_ts:new Date(Number(d.internalDate)).toISOString(),labels:d.labelIds,display_url:`https://mail.google.com/mail/u/${encodeURIComponent(account)}/#inbox/${d.id}`};}));for(const r of batch)if(r.status==="fulfilled")emails.push(r.value);else{if(r.reason?.retryAfterMs)throw r.reason;payload.partial=true;notes.push("Some inbox message summaries could not be read.");}}
  payload.emails=normalizeEmails({emails},"gmail");payload.partial=payload.partial||!!listed.nextPageToken;notes.push("Latest 40 inbox candidates. Importance signals are rules, not confirmed commitments.");
 }else{
  const listed=await api("/v1.0/me/mailFolders/inbox/messages?$top=40&$orderby=receivedDateTime%20desc&$select=id,subject,from,bodyPreview,receivedDateTime,importance,isRead,webLink");payload.emails=normalizeEmails({value:(listed.value||[]).map((e:any)=>({...e,sender:e.from,web_link:e.webLink}))},"unityMail");payload.partial=!!listed["@odata.nextLink"];notes.push("Latest 40 inbox candidates. Importance signals are rules, not confirmed commitments.");
 }
 const prefix=snapshotKey.startsWith("account:")?`${snapshotKey}:`:"";payload.events=[...new Map(payload.events.map((e:any)=>[e.id,e])).values()].map((e:any)=>({...e,id:prefix+e.id,lane}));payload.emails=payload.emails.map((e:any)=>({...e,id:prefix+e.id,lane}));const updatedAt=await saveSnapshot(owner,snapshotKey,payload);return {status:"success",payload:{...payload,updatedAt}};
}
