import test from 'node:test';import assert from 'node:assert/strict';import {prioritize} from './prioritization.mjs';import {dayAt} from './planning.mjs';
const now=dayAt('2026-10-09',9),prefs={startHour:9,endHour:17};
const task=(id,patch={})=>({id,title:id,status:'open',minutes:60,deadline:'2026-10-20',delayImpact:'unknown',peopleBlocked:false,...patch});
const rank=(tasks,events=[],blocks=[],extra={})=>prioritize(tasks,events,blocks,{...prefs,...extra},now);
test('recorded consequences and held-up people outrank a merely named stakeholder',()=>{const tasks=[task('named',{stakeholder:'President'}),task('blocked',{peopleBlocked:true,stakeholder:'Colleague'}),task('safety',{delayImpact:'safety'})];assert.deepEqual(rank(tasks).next.map(r=>r.task.id),['safety','blocked','named']);assert(rank(tasks).next[1].reasons.includes('Colleague is held up'));});
test('waiting tasks and zero-estimate parents do not displace actionable subtasks',()=>{const r=rank([task('waiting',{status:'waiting',delayImpact:'safety'}),task('parent',{minutes:0}),task('child',{parentId:'parent'}),task('done',{status:'done'})]);assert.deepEqual(r.next.map(r=>r.task.id),['child']);assert.equal(r.followUp[0].id,'waiting');assert.equal(r.clarify[0].task.id,'parent');});
test('calendar occupancy changes deadline pressure without rewarding easy tasks over consequence',()=>{const tasks=[task('long',{minutes:300,deadline:'2026-10-09'}),task('small',{minutes:15,deadline:'2026-10-09'})];const busy=[{busy:true,start:new Date(dayAt('2026-10-09',9)).toISOString(),end:new Date(dayAt('2026-10-09',15)).toISOString()}];const empty=rank(tasks),packed=rank(tasks,busy);assert(packed.next.find(r=>r.task.id==='long').score>empty.next.find(r=>r.task.id==='long').score);assert(packed.next.find(r=>r.task.id==='long').reasons.includes('Remaining work exceeds time available before due date'));});
test('a chosen actionable task comes first; completed and waiting choices do not enter work queue',()=>{const tasks=[task('chosen'),task('exposure',{delayImpact:'safety'})];assert.equal(rank(tasks,[],[],{focusTaskId:'chosen'}).next[0].task.id,'chosen');tasks[0].status='done';assert.equal(rank(tasks,[],[],{focusTaskId:'chosen'}).next[0].task.id,'exposure');});
test('parent deadlines constrain subtasks and protected time is not double-subtracted',()=>{const tasks=[task('parent',{minutes:0,deadline:'2026-10-09'}),task('child',{parentId:'parent',deadline:'2026-10-20',minutes:60})],block={taskId:'child',start:new Date(now).toISOString(),end:new Date(now+3600000).toISOString()};const r=rank(tasks,[],[block]).next[0];assert.equal(r.deadline,'2026-10-09');assert.equal(r.capacityMinutes,480);assert(r.underway);assert(r.reasons.includes('Protected work block is underway'));});
