import { allSourceInfo } from "../../lib/connections";
import { authorize,json } from "../../lib/api";
import { readState,saveTask,saveBlock,taskSchema,blockSchema,saveWorkLog,workLogSchema } from "../../lib/repository";
import { analyze } from "../../lib/planning.mjs";
export const dynamic="force-dynamic";
const taskProperties={id:{type:"string",description:"A UUID; reuse it when updating a task"},title:{type:"string"},project:{type:"string"},lane:{type:"string",enum:["Unity Homes","AthenaWorx","SHP Beds","Personal"]},stakeholder:{type:"string"},deadline:{type:"string",description:"YYYY-MM-DD in America/Phoenix"},minutes:{type:"integer",description:"Remaining own-work estimate, minimum 0; use 0 for a parent whose work is entirely in subtasks"},status:{type:"string",enum:["open","doing","waiting","done"]},lifeHealthSafety:{type:"boolean"},securityPrivacy:{type:"boolean"},important:{type:["boolean","null"]},dependsOn:{type:"array",items:{type:"string"},description:"UUIDs of prerequisite commitments that must be complete before this task; only record confirmed dependencies"},delayImpact:{type:"string",enum:["unknown","people","service","financial","safety","opportunity"]},peopleBlocked:{type:"boolean"},delayConsequence:{type:"string"},output:{type:"string"},sourceUrl:{type:"string"},parentId:{type:["string","null"],description:"Optional parent commitment UUID; null detaches. Remaining minutes cover this task only."}};
const tools=[{name:"log_task_work",description:"Record an actual work session for the user’s commitment, including on completion. Use confirmed elapsed minutes; AI-assisted minutes are a subset, not extra time. Record skills actually used and the result. Never infer hours from message counts or claim estimated AI time savings. Obtain user confirmation of uncertain duration before saving. Reuse id for retries; entries are append-only.",inputSchema:{type:"object",properties:{id:{type:"string",description:"UUID idempotency key"},taskId:{type:"string"},workedOn:{type:"string",description:"YYYY-MM-DD in America/Phoenix"},minutes:{type:"integer",minimum:1,maximum:1440},aiMinutes:{type:"integer",minimum:0,maximum:1440},skills:{type:"array",items:{type:"string"}},notes:{type:"string",description:"Work performed and output"}},required:["id","taskId","workedOn","minutes","aiMinutes","skills","notes"],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},{name:"read_commitments",description:"Read the signed-in user's Partheanon tasks, work blocks, preferences, and cached calendar/mail summaries. Check source timestamps; caches can be stale or partial.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},{name:"analyze_workload",description:"Compute conflicts and deadline capacity from cached calendars and tasks. Does not see unconnected accounts. Default work hours are weekdays 9–17 Phoenix with 15-minute calendar buffers.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},{name:"save_commitment",description:"Create or update a commitment after the user authorizes the task and deadline. id is the idempotency key. Does not send messages or change external calendars.",inputSchema:{type:"object",properties:taskProperties,required:Object.keys(taskProperties).filter(k=>!["lifeHealthSafety","securityPrivacy","important","dependsOn","parentId","delayImpact","peopleBlocked","delayConsequence"].includes(k)),additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}},{name:"protect_work_block",description:"Reserve a block in Partheanon for an active task after the user authorizes it. Check recent calendars and collisions first. Does not write to external calendars. Reuse UUID id for duplicate requests.",inputSchema:{type:"object",properties:{id:{type:"string"},taskId:{type:"string"},title:{type:"string"},start:{type:"string"},end:{type:"string"}},required:["id","taskId","title","start","end"],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true}}];
export async function POST(r:Request){let body:any;try{body=await r.json();const reply=(result:any)=>json({jsonrpc:"2.0",id:body.id??null,result});if(body.method==="initialize")return reply({protocolVersion:"2024-11-05",capabilities:{tools:{}},serverInfo:{name:"Partheanon",version:"1.0.0"}});if(body.method==="notifications/initialized")return new Response(null,{status:204});if(body.method==="ping")return reply({});if(body.method==="tools/list")return reply({tools});if(body.method!=="tools/call")return json({jsonrpc:"2.0",id:body.id??null,error:{code:-32601,message:"Method not found"}});
 const owner=await authorize(r,false);let result;const name=body.params?.name,args=body.params?.arguments||{};
 if(name==="log_task_work")result=await saveWorkLog(owner,workLogSchema.parse(args));else if(name==="read_commitments")result=await readState(owner);else if(name==="analyze_workload"){const state=await readState(owner);result={...analyze(state.tasks,Object.entries(state.sources).filter(([k])=>allSourceInfo(state.connections)[k]?.kind==="calendar").flatMap(([,s]:any)=>s.events||[]),state.blocks,state.preferences),sourceFreshness:Object.fromEntries(Object.entries(state.sources).map(([k,s]:any)=>[k,{updatedAt:s.updatedAt,partial:s.partial}]))};}else if(name==="save_commitment")result=await saveTask(owner,taskSchema.parse(args));else if(name==="protect_work_block")result=await saveBlock(owner,blockSchema.parse(args));else throw new Error("Unknown tool");
 return reply({content:[{type:"text",text:JSON.stringify(result)}],structuredContent:result});
 }catch(e){const message=e instanceof Error?e.message:"Request failed";if(message.includes("Sign in"))return json({error:message},401);return json({jsonrpc:"2.0",id:body?.id??null,result:{isError:true,content:[{type:"text",text:message}]}});}}
